using System.Collections.Generic;
using UnityEngine;

/// <summary>
/// Represents a table in the restaurant with capacity and seat points for clients.
/// </summary>
public class Table : MonoBehaviour
{
    [Header("Table Properties")]
    public int tableNumber = 1;

    [Header("Chair-Based Capacity")]
    [Tooltip("Distance from the table center to check for chairs on each side.")]
    public float chairDetectionDistance = 1.1f;
    [Tooltip("Radius of the detection sphere at each side.")]
    public float chairDetectionRadius = 0.5f;
    [Tooltip("Layer where chairs are located for detection.")]
    public LayerMask chairLayer;

    [SerializeField] private List<Chair> _registeredChairs = new();
    private float _nextScanTime = 0f;
    private const float SCAN_INTERVAL = 0.5f;

    [Header("Food Placement")]
    [Tooltip("Transform point where food will be placed. If null, table center will be used.")]
    public Transform foodPoint;

    [Header("Auto-Generation (Fallback / Debug)")]
    [Tooltip("If true and no chairs are registered, auto-generate seat points for testing.")]
    public bool autoGenerateSeats = false;
    public float seatRadius = 1.5f;
    private List<Transform> _autoGeneratedSeats = new();

    public int Capacity
    {
        get
        {
            if (_registeredChairs.Count > 0) return _registeredChairs.Count;
            if (autoGenerateSeats && _autoGeneratedSeats.Count > 0) return _autoGeneratedSeats.Count;

            // no chairs = no seats
            return 0;
        }
    }

    public bool IsOccupied { get; private set; }
    public ClientGroup OccupyingGroup { get; private set; }

    public bool IsPlaced { get; private set; }

    private PlaceableObject _placeable;
    private bool _isCarried;

    void Awake()
    {
        if (_registeredChairs == null) _registeredChairs = new List<Chair>();

        if (autoGenerateSeats)
        {
        }
    }

    void Start()
    {
        _placeable = GetComponent<PlaceableObject>();
        RestaurantManager.Instance?.RegisterTable(this);

        IsPlaced = true;
        RestaurantManager.Instance?.TablePlaced(this);
    }

    void Update()
    {
        if (Time.time >= _nextScanTime)
        {
            _nextScanTime = Time.time + SCAN_INTERVAL;
            ScanForChairs();
        }
    }

    void OnDestroy()
    {
        if (IsPlaced)
        {
            RestaurantManager.Instance?.TableStored(this);
        }
        RestaurantManager.Instance?.UnregisterTable(this);
    }

    public void Reserve(ClientGroup group)
    {
        if (group == null) return;

        if (group.Size > Capacity)
        {
            Debug.LogWarning($"[Table {tableNumber}] Group size {group.Size} exceeds capacity {Capacity}!");
        }

        IsOccupied = true;
        OccupyingGroup = group;
        Debug.Log($"[Table {tableNumber}] Reserved for {group}");
    }

    public void FreeTable(ClientGroup group)
    {
        if (!IsOccupied || OccupyingGroup != group) return;

        RestaurantManager.Instance?.FreeGroupTables(group);
    }

    public void ClearReservation()
    {
        IsOccupied = false;
        OccupyingGroup = null;
        Debug.Log($"[Table {tableNumber}] Freed");
    }

    // carried by the player; while lifted it leaves the seating pool
    public void SetCarried(bool carried)
    {
        _isCarried = carried;
        IsPlaced = !carried;
        if (carried)
            RestaurantManager.Instance?.TableStored(this);
        else
            RestaurantManager.Instance?.TablePlaced(this);
    }

    public void ScanForChairs()
    {
        if (_isCarried) return;
        if (!IsPlaced)
        {
            if (_registeredChairs.Count > 0)
            {
                _registeredChairs.Clear();
                RestaurantManager.Instance?.TablePlaced(this);
            }
            return;
        }

        int previousCount = _registeredChairs.Count;
        _registeredChairs.Clear();

        Vector3[] directions = { transform.forward, -transform.forward, transform.right, -transform.right };

        foreach (Vector3 dir in directions)
        {
            if (_registeredChairs.Count >= 4) break;

            Vector3 checkPos = transform.position + dir * chairDetectionDistance;
            Collider[] hits = Physics.OverlapSphere(checkPos, chairDetectionRadius, chairLayer);

            Chair bestChair = null;
            float bestDist = float.MaxValue;

            foreach (Collider hit in hits)
            {
                Chair chair = hit.GetComponentInParent<Chair>();
                if (chair == null || !chair.IsPlaced) continue;

                if (_registeredChairs.Contains(chair)) continue;

                float dist = Vector3.Distance(checkPos, chair.transform.position);
                if (dist < bestDist)
                {
                    bestDist = dist;
                    bestChair = chair;
                }
            }

            if (bestChair != null)
            {
                _registeredChairs.Add(bestChair);
            }
        }

        if (_registeredChairs.Count != previousCount)
        {
            Debug.Log($"[Table {tableNumber}] Capacity changed: {_registeredChairs.Count}");
            RestaurantManager.Instance?.TablePlaced(this);
        }
    }

    public void RegisterChair(Chair chair) { ScanForChairs(); }

    public void UnregisterChair(Chair chair) { ScanForChairs(); }

    public List<Transform> GetSeatPoints()
    {
        if (_registeredChairs.Count > 0)
        {
            List<Transform> seats = new List<Transform>(_registeredChairs.Count);
            foreach (Chair c in _registeredChairs)
            {
                if (c != null)
                    seats.Add(c.SeatTransform);
            }
            if (seats.Count > 0)
                return seats;
        }

        // no chairs: only autogen seats if the debug flag is on
        if (!autoGenerateSeats) return new List<Transform>();

        if (_autoGeneratedSeats.Count == 0)
            GenerateSeatPoints();
        return _autoGeneratedSeats;
    }
    // free, still-placed chair here — for re-seating after a seat is carried off
    public Transform GetFreeSeatPoint()
    {
        foreach (Chair c in _registeredChairs)
            if (c != null && c.IsPlaced && c.Occupant == null)
                return c.SeatTransform;
        return null;
    }

    public bool CanPlaceFood()
    {
        if (!IsOccupied || OccupyingGroup == null) return false;

        // One plate feeds one diner: we can keep placing while the group is not
        // yet fully fed (and at least one member is still waiting for food).
        if (OccupyingGroup.AllFed) return false;

        foreach (var member in OccupyingGroup.Members)
        {
            if (member != null && member.CurrentState == Client.State.WaitingForFood)
                return true;
        }

        return false;
    }

    /// <summary>Serves a plate to the seated group. Returns true if accepted
    /// (player drops the plate), false if rejected (wrong dish — plate stays in
    /// the player's hands so they can take it to the right table).</summary>
    public bool PlaceFood(Food food)
    {
        if (food == null || OccupyingGroup == null) return false;
        ClientGroup g = OccupyingGroup;

        // ── Order check: reject a dish the group didn't order ──
        if (!g.WantsRecipe(food.recipe))
        {
            RejectOrder(food);
            return false;
        }

        // One plate feeds one or two diners: a group may share dishes, in which
        // case the last plate of the order feeds two diners. Feed that many
        // still-waiting diners from the group.
        int dinersToFeed = g.DinersForNextPlate();
        if (dinersToFeed <= 0) return false;

        int fed = 0;
        foreach (var member in g.Members)
        {
            if (member != null && member.CurrentState == Client.State.WaitingForFood)
            {
                member.ReceiveFood();
                fed++;
                if (fed >= dinersToFeed) break;
            }
        }
        if (fed == 0) return false; // nobody waiting — shouldn't happen (CanPlaceFood guards)

        // Count the plate, consume one matching order slot, refill patience.
        g.OnPlateServed();
        g.TryConsumeOrder(food.recipe);

        // Stack plates in a small 2x2 grid on the food point so multiple plates
        // don't overlap when serving a group of several diners.
        Transform targetPoint = foodPoint != null ? foodPoint : this.transform;
        food.PlaceOnTable(targetPoint);
        int idx = g.PlatesServed - 1; // already incremented above
        Vector3 off = new Vector3((idx % 2) * 0.35f - 0.175f, 0f, (idx / 2) * 0.35f - 0.175f);
        food.transform.localPosition = off;

        Debug.Log($"[Table {tableNumber}] Food {food.foodName} served ({g.PlatesServed}/{g.PlatesNeeded}, fed {fed} diners{(g.IsSharing ? ", sharing" : "")}) to group {g.GroupID}");
        return true;
    }

    /// <summary>Called when the player serves a dish the group didn't order.
    /// Small patience penalty + feedback; the plate stays in the player's hands
    /// (PlaceFood returns false, so PlayerController keeps holding it).</summary>
    private void RejectOrder(Food food)
    {
        ClientGroup g = OccupyingGroup;
        // Knock a few seconds off the patience bar as a penalty (reuse the
        // existing tick; TickPatience ignores the return — we're not angering
        // the whole group over one wrong plate, just nudging the bar).
        g?.TickPatience(5f);

        string dishLabel = food.recipe != null ? food.recipe.dishName : food.foodName;
        HUDMessage.Instance?.ShowWarning($"¡La mesa {tableNumber} no ha pedido {dishLabel}!");
        AudioManager.Instance?.PlaySFX("client_angry");
        Debug.Log($"[Table {tableNumber}] Rejected {dishLabel}: not on the order for group {g?.GroupID}.");
    }

    private void GenerateSeatPoints()
    {

        foreach (Transform s in _autoGeneratedSeats)
            if (s != null) Destroy(s.gameObject);
        _autoGeneratedSeats.Clear();

        int count = Capacity > 0 ? Capacity : 4;
        for (int i = 0; i < count; i++)
        {
            GameObject seatObj = new GameObject($"AutoSeat_{tableNumber}_{i + 1}");
            seatObj.transform.SetParent(transform);

            float angle = (360f / count) * i;
            float radians = angle * Mathf.Deg2Rad;
            Vector3 offset = new Vector3(
                Mathf.Cos(radians) * seatRadius,
                0f,
                Mathf.Sin(radians) * seatRadius
            );
            seatObj.transform.localPosition = offset;
            _autoGeneratedSeats.Add(seatObj.transform);
        }

        Debug.Log($"[Table {tableNumber}] Auto-generated {count} fallback seat points.");
    }


    void OnDrawGizmosSelected()
    {
        Gizmos.color = IsOccupied ? Color.red : (Capacity > 0 ? Color.green : Color.gray);

        Vector3[] directions = { transform.forward, -transform.forward, transform.right, -transform.right };
        foreach (Vector3 dir in directions)
        {
            Vector3 checkPos = transform.position + dir * chairDetectionDistance;
            Gizmos.color = Color.cyan;
            Gizmos.DrawWireSphere(checkPos, chairDetectionRadius);
        }

        if (_registeredChairs != null)
        {
            Gizmos.color = Color.green;
            foreach (Chair c in _registeredChairs)
            {
                if (c != null)
                {
                    Gizmos.DrawWireSphere(c.SeatTransform.position, 0.3f);
                    Gizmos.DrawLine(transform.position, c.SeatTransform.position);
                }
            }
        }

        if (_autoGeneratedSeats != null)
        {
            Gizmos.color = Color.yellow;
            foreach (Transform seat in _autoGeneratedSeats)
            {
                if (seat != null)
                {
                    Gizmos.DrawWireSphere(seat.position, 0.3f);
                    Gizmos.DrawLine(transform.position, seat.position);
                }
            }
        }

        Gizmos.color = Color.white;
        Gizmos.DrawWireSphere(transform.position, 0.15f);
    }
}