using System.Collections.Generic;
using UnityEngine;

/// <summary>Variant of a seating furniture.
/// <list type="bullet">
/// <item><see cref="TableVariant.Regular"/>: classic table. One group claims the
/// whole table (and grouped tables in a block).</item>
/// <item><see cref="TableVariant.BarStand"/>: bar counter with stools. A group
/// only claims the stools it needs; several groups share the same bar.</item>
/// </list></summary>
public enum TableVariant
{
    Regular,
    BarStand,
}

/// <summary>
/// Represents a table in the restaurant with capacity and seat points for clients.
/// </summary>
public class Table : MonoBehaviour
{
    [Header("Table Properties")]
    public int tableNumber = 1;

    [Header("Variant")]
    [Tooltip("Regular: mesa clásica — un grupo ocupa la mesa entera (y los bloques de mesas juntas). " +
             "BarStand: barra con taburetes — cada grupo SOLO reserva los taburetes que necesita y " +
             "puede compartir la barra con otros grupos a la vez.")]
    public TableVariant variant = TableVariant.Regular;

    /// <summary>True when this furniture is a bar stand (counter + stools).</summary>
    public bool IsBarStand => variant == TableVariant.BarStand;

    [Header("Chair-Based Capacity")]
    [Tooltip("Distance from the table center to check for chairs on each side.")]
    public float chairDetectionDistance = 1.1f;
    [Tooltip("Radius of the detection sphere at each side.")]
    public float chairDetectionRadius = 0.5f;
    [Tooltip("Layer where chairs are located for detection.")]
    public LayerMask chairLayer;

    [SerializeField] private List<Chair> _registeredChairs = new();
    private float _nextScanTime = 0f;
    private const float SCAN_INTERVAL = 0.5f;

    [Header("Bar Stand")]
    [Tooltip("Máximo de taburetes que una barra registra a la vez. El reparto por columnas " +
             "evita que dos tramos de barra contiguos reclamen el mismo taburete.")]
    public int maxBarStools = 8;

    // Bar stand only: for each seated group, the stools it has booked.
    // A bar is never claimed wholesale: other groups can book the free stools.
    private readonly Dictionary<ClientGroup, List<Chair>> _barGroupSeats = new();

    // Regular only: the single group occupying this table.
    private bool _regularOccupied;
    private ClientGroup _regularGroup;

    [Header("Food Placement")]
    [Tooltip("Transform point where food will be placed. If null, table center will be used.")]
    public Transform foodPoint;

    [Header("Auto-Generation (Fallback / Debug)")]
    [Tooltip("If true and no chairs are registered, auto-generate seat points for testing.")]
    public bool autoGenerateSeats = false;
    public float seatRadius = 1.5f;
    private List<Transform> _autoGeneratedSeats = new();

    public int Capacity
    {
        get
        {
            if (_registeredChairs.Count > 0) return _registeredChairs.Count;
            if (autoGenerateSeats && _autoGeneratedSeats.Count > 0) return _autoGeneratedSeats.Count;

            // no chairs = no seats
            return 0;
        }
    }

    /// <summary>True when a group is seated here. For bar stands this means at
    /// least one group is using some of the stools.</summary>
    public bool IsOccupied => IsBarStand ? _barGroupSeats.Count > 0 : _regularOccupied;

    // Regular: the occupying group. Bar stand: the most urgent group still
    // waiting for food (used by the single patience/order HUD widgets on the
    // furniture; the ticket rail and guides use SeatedGroups instead).
    public ClientGroup OccupyingGroup
    {
        get
        {
            if (!IsBarStand) return _regularGroup;

            ClientGroup best = null;
            foreach (ClientGroup g in _barGroupSeats.Keys)
            {
                if (g == null || !g.IsWaitingForFood) continue;
                if (best == null || g.PatienceRatio < best.PatienceRatio) best = g;
            }
            return best;
        }
    }

    /// <summary>Every group currently seated at this table (one for regular
    /// tables, several for a shared bar stand).</summary>
    public IEnumerable<ClientGroup> SeatedGroups
    {
        get
        {
            if (IsBarStand) return _barGroupSeats.Keys;
            return _regularGroup != null ? SingleGroup(_regularGroup) : EmptyGroups;
        }
    }

    private static readonly ClientGroup[] EmptyGroups = new ClientGroup[0];
    private static IEnumerable<ClientGroup> SingleGroup(ClientGroup g) { yield return g; }

    public bool HasGroup(ClientGroup group)
    {
        if (group == null) return false;
        return IsBarStand ? _barGroupSeats.ContainsKey(group) : _regularGroup == group;
    }

    /// <summary>Stools still bookable at a bar stand (0 when the bar is full);
    /// for regular tables it's the full capacity while free, 0 while occupied.</summary>
    public int FreeSeats
    {
        get
        {
            if (!IsBarStand) return IsOccupied ? 0 : Capacity;
            int used = 0;
            foreach (var kv in _barGroupSeats) used += kv.Value.Count;
            return Mathf.Max(0, Capacity - used);
        }
    }

    public bool IsPlaced { get; private set; }

    private PlaceableObject _placeable;
    private bool _isCarried;

    void Awake()
    {
        if (_registeredChairs == null) _registeredChairs = new List<Chair>();

        if (autoGenerateSeats)
        {
        }
    }

    void Start()
    {
        _placeable = GetComponent<PlaceableObject>();
        RestaurantManager.Instance?.RegisterTable(this);

        IsPlaced = true;
        RestaurantManager.Instance?.TablePlaced(this);
    }

    void Update()
    {
        if (Time.time >= _nextScanTime)
        {
            _nextScanTime = Time.time + SCAN_INTERVAL;
            ScanForChairs();
        }
    }

    void OnDestroy()
    {
        if (IsPlaced)
        {
            RestaurantManager.Instance?.TableStored(this);
        }
        RestaurantManager.Instance?.UnregisterTable(this);
    }

    /// <summary>Regular tables only: the whole table belongs to one group.
    /// Bar stands book individual stools via <see cref="BookSeats"/>.</summary>
    public void Reserve(ClientGroup group)
    {
        if (group == null) return;

        if (IsBarStand)
        {
            Debug.LogWarning($"[Table {tableNumber}] BarStand usa BookSeats, no Reserve.");
            return;
        }

        if (group.Size > Capacity)
        {
            Debug.LogWarning($"[Table {tableNumber}] Group size {group.Size} exceeds capacity {Capacity}!");
        }

        _regularOccupied = true;
        _regularGroup = group;
        Debug.Log($"[Table {tableNumber}] Reserved for {group}");
    }

    public void FreeTable(ClientGroup group)
    {
        if (group == null) return;
        if (IsBarStand)
        {
            // A bar is freed group by group, through RestaurantManager (it also
            // flushes waiting groups so the stools can be reused immediately).
            if (!_barGroupSeats.ContainsKey(group)) return;
            RestaurantManager.Instance?.FreeGroupTables(group);
            return;
        }
        if (!_regularOccupied || _regularGroup != group) return;

        RestaurantManager.Instance?.FreeGroupTables(group);
    }

    public void ClearReservation()
    {
        _regularOccupied = false;
        _regularGroup = null;
        Debug.Log($"[Table {tableNumber}] Freed");
    }

    /// <summary>Bar stands only: books up to <paramref name="count"/> free stools
    /// for <paramref name="group"/> and returns their seat transforms. Other
    /// groups can keep using the remaining stools.</summary>
    public List<Transform> BookSeats(ClientGroup group, int count)
    {
        var seats = new List<Transform>();
        if (group == null || count <= 0 || _barGroupSeats.ContainsKey(group)) return seats;

        var booked = new List<Chair>(count);
        foreach (Chair stool in _registeredChairs)
        {
            if (booked.Count >= count) break;
            if (stool == null || !stool.IsPlaced) continue;
            if (IsStoolBooked(stool)) continue;

            booked.Add(stool);
            seats.Add(stool.SeatTransform);
        }

        if (booked.Count == 0)
        {
            // Normal when the group is booked across several counter segments
            // and this segment has no free stool left.
            return seats;
        }

        _barGroupSeats[group] = booked;
        Debug.Log($"[Table {tableNumber}] Barra: {booked.Count} taburete(s) reservados para {group}.");
        return seats;
    }

    /// <summary>Bar stands only: releases the stools booked by <paramref name="group"/>.</summary>
    public bool ReleaseGroup(ClientGroup group)
    {
        if (group == null || !_barGroupSeats.TryGetValue(group, out var booked)) return false;
        _barGroupSeats.Remove(group);

        // Free the stools we booked for the group...
        foreach (Chair stool in booked)
            if (stool != null && stool.Occupant != null && stool.Occupant.Group == group)
                stool.Occupant = null;

        // ...and any registered stool whose occupant belongs to the group
        // (covers mid-walk re-seats onto stools this table did not book).
        foreach (Chair stool in _registeredChairs)
            if (stool != null && stool.Occupant != null && stool.Occupant.Group == group)
                stool.Occupant = null;

        Debug.Log($"[Table {tableNumber}] Barra liberada de {group} ({booked.Count} taburetes).");
        return true;
    }

    private bool IsStoolBooked(Chair stool)
    {
        if (stool.Occupant != null) return true;
        foreach (var kv in _barGroupSeats)
            if (kv.Value.Contains(stool)) return true;
        return false;
    }

    /// <summary>Which seated group a served plate is meant for. Regular tables:
    /// the occupying group. Bar stands: the first seated group whose order
    /// matches the dish (fallback: the group with the least patience).</summary>
    public ClientGroup GetServeTarget(Food food)
    {
        if (!IsBarStand) return _regularGroup;

        ClientGroup fallback = null;
        foreach (ClientGroup g in _barGroupSeats.Keys)
        {
            if (g == null || g.AllFed) continue;

            bool waiting = false;
            foreach (var m in g.Members)
                if (m != null && m.CurrentState == Client.State.WaitingForFood) { waiting = true; break; }
            if (!waiting) continue;

            if (food != null && food.recipe != null && g.WantsRecipe(food.recipe))
                return g;

            if (fallback == null || g.PatienceRatio < fallback.PatienceRatio)
                fallback = g;
        }
        return fallback;
    }

    // carried by the player; while lifted it leaves the seating pool
    public void SetCarried(bool carried)
    {
        _isCarried = carried;
        IsPlaced = !carried;
        if (carried)
            RestaurantManager.Instance?.TableStored(this);
        else
            RestaurantManager.Instance?.TablePlaced(this);
    }

    public void ScanForChairs()
    {
        if (_isCarried) return;
        if (!IsPlaced)
        {
            if (_registeredChairs.Count > 0)
            {
                _registeredChairs.Clear();
                RestaurantManager.Instance?.TablePlaced(this);
            }
            return;
        }

        int previousCount = _registeredChairs.Count;

        if (IsBarStand)
        {
            ScanBarStools();
        }
        else
        {
            _registeredChairs.Clear();

            Vector3[] directions = { transform.forward, -transform.forward, transform.right, -transform.right };

            foreach (Vector3 dir in directions)
            {
                if (_registeredChairs.Count >= 4) break;

                Vector3 checkPos = transform.position + dir * chairDetectionDistance;
                Collider[] hits = Physics.OverlapSphere(checkPos, chairDetectionRadius, chairLayer);

                Chair bestChair = null;
                float bestDist = float.MaxValue;

                foreach (Collider hit in hits)
                {
                    Chair chair = hit.GetComponentInParent<Chair>();
                    if (chair == null || !chair.IsPlaced) continue;

                    if (_registeredChairs.Contains(chair)) continue;

                    float dist = Vector3.Distance(checkPos, chair.transform.position);
                    if (dist < bestDist)
                    {
                        bestDist = dist;
                        bestChair = chair;
                    }
                }

                if (bestChair != null)
                {
                    _registeredChairs.Add(bestChair);
                }
            }
        }

        if (_registeredChairs.Count != previousCount)
        {
            Debug.Log($"[Table {tableNumber}] Capacity changed: {_registeredChairs.Count}");
            RestaurantManager.Instance?.TablePlaced(this);
        }
    }

    /// <summary>Bar stands scan for stools along the counter instead of the four
    /// chair spots. A stool belongs to the counter cell directly in front of it:
    /// same grid column (local X ≈ 0) and one cell away (|Z| ≈ 1). Adjacent
    /// counter segments never claim the same stool, so a long bar keeps one
    /// stool per cell and several cells form one shared counter block.</summary>
    private void ScanBarStools()
    {
        _registeredChairs.Clear();

        float scanRadius = chairDetectionDistance + chairDetectionRadius + 0.5f;
        foreach (Collider hit in Physics.OverlapSphere(transform.position, scanRadius, chairLayer))
        {
            if (_registeredChairs.Count >= maxBarStools) break;

            Chair stool = hit.GetComponentInParent<Chair>();
            if (stool == null || !stool.IsPlaced) continue;

            Vector3 flat = stool.transform.position - transform.position;
            flat.y = 0f;

            if (Mathf.Abs(flat.x) > 0.55f) continue;                 // stool of a neighbour cell
            float depth = Mathf.Abs(flat.z);
            // Own stools sit one cell away (depth ≈ 1); a stool two cells away
            // (a counter stacked along Z) is the neighbour segment's own.
            if (depth < 0.45f || depth > chairDetectionDistance + 0.5f) continue;

            _registeredChairs.Add(stool);
        }

        // Deterministic left→right order: groups book stools along the counter.
        _registeredChairs.Sort((a, b) =>
        {
            int byX = a.transform.position.x.CompareTo(b.transform.position.x);
            return byX != 0 ? byX : a.transform.position.z.CompareTo(b.transform.position.z);
        });
    }

    public void RegisterChair(Chair chair) { ScanForChairs(); }

    public void UnregisterChair(Chair chair) { ScanForChairs(); }

    public List<Transform> GetSeatPoints()
    {
        if (_registeredChairs.Count > 0)
        {
            List<Transform> seats = new List<Transform>(_registeredChairs.Count);
            foreach (Chair c in _registeredChairs)
            {
                if (c != null)
                    seats.Add(c.SeatTransform);
            }
            if (seats.Count > 0)
                return seats;
        }

        // no chairs: only autogen seats if the debug flag is on
        if (!autoGenerateSeats) return new List<Transform>();

        if (_autoGeneratedSeats.Count == 0)
            GenerateSeatPoints();
        return _autoGeneratedSeats;
    }
    // free, still-placed chair here — for re-seating after a seat is carried off
    public Transform GetFreeSeatPoint()
    {
        foreach (Chair c in _registeredChairs)
            if (c != null && c.IsPlaced && !IsStoolBooked(c))
                return c.SeatTransform;
        return null;
    }

    public bool CanPlaceFood()
    {
        foreach (ClientGroup g in SeatedGroups)
        {
            if (g == null || g.AllFed) continue;

            // One plate feeds one diner: we can keep placing while the group is not
            // yet fully fed (and at least one member is still waiting for food).
            foreach (var member in g.Members)
            {
                if (member != null && member.CurrentState == Client.State.WaitingForFood)
                    return true;
            }
        }

        return false;
    }

    /// <summary>Serves a plate to the seated group. Returns true if accepted
    /// (player drops the plate), false if rejected (wrong dish — plate stays in
    /// the player's hands so they can take it to the right table).</summary>
    public bool PlaceFood(Food food)
    {
        if (food == null) return false;
        ClientGroup g = GetServeTarget(food);
        if (g == null) return false;

        // ── Order check: reject a dish the group didn't order ──
        if (!g.WantsRecipe(food.recipe))
        {
            RejectOrder(food, g);
            return false;
        }

        // One plate feeds one or two diners: a group may share dishes, in which
        // case the last plate of the order feeds two diners. Feed that many
        // still-waiting diners from the group.
        int dinersToFeed = g.DinersForNextPlate();
        if (dinersToFeed <= 0) return false;

        int fed = 0;
        foreach (var member in g.Members)
        {
            if (member != null && member.CurrentState == Client.State.WaitingForFood)
            {
                member.ReceiveFood();
                food.RegisterFedMember(member);
                fed++;
                if (fed >= dinersToFeed) break;
            }
        }
        if (fed == 0) return false; // nobody waiting — shouldn't happen (CanPlaceFood guards)

        // Count the plate, consume one matching order slot, refill patience.
        g.OnPlateServed();
        g.TryConsumeOrder(food.recipe);

        // Stack plates in a small 2x2 grid on the food point so multiple plates
        // don't overlap when serving a group of several diners.
        Transform targetPoint = foodPoint != null ? foodPoint : this.transform;
        food.PlaceOnTable(targetPoint);
        int idx = g.PlatesServed - 1; // already incremented above
        Vector3 off = new Vector3((idx % 2) * 0.35f - 0.175f, 0f, (idx / 2) * 0.35f - 0.175f);
        food.transform.localPosition = off;

        Debug.Log($"[Table {tableNumber}] Food {food.foodName} served ({g.PlatesServed}/{g.PlatesNeeded}, fed {fed} diners{(g.IsSharing ? ", sharing" : "")}) to group {g.GroupID}");
        return true;
    }

    /// <summary>Called when the player serves a dish the group didn't order.
    /// Small patience penalty + feedback; the plate stays in the player's hands
    /// (PlaceFood returns false, so PlayerController keeps holding it).</summary>
    private void RejectOrder(Food food, ClientGroup g)
    {
        // Knock a few seconds off the patience bar as a penalty (reuse the
        // existing tick; TickPatience ignores the return — we're not angering
        // the whole group over one wrong plate, just nudging the bar).
        g?.TickPatience(5f);

        string dishLabel = food.recipe != null ? food.recipe.dishName : food.foodName;
        HUDMessage.Instance?.ShowWarning($"¡La mesa {tableNumber} no ha pedido {dishLabel}!");
        AudioManager.Instance?.PlaySFX("client_angry");
        Debug.Log($"[Table {tableNumber}] Rejected {dishLabel}: not on the order for group {g?.GroupID}.");
    }

    private void GenerateSeatPoints()
    {

        foreach (Transform s in _autoGeneratedSeats)
            if (s != null) Destroy(s.gameObject);
        _autoGeneratedSeats.Clear();

        int count = Capacity > 0 ? Capacity : 4;
        for (int i = 0; i < count; i++)
        {
            GameObject seatObj = new GameObject($"AutoSeat_{tableNumber}_{i + 1}");
            seatObj.transform.SetParent(transform);

            float angle = (360f / count) * i;
            float radians = angle * Mathf.Deg2Rad;
            Vector3 offset = new Vector3(
                Mathf.Cos(radians) * seatRadius,
                0f,
                Mathf.Sin(radians) * seatRadius
            );
            seatObj.transform.localPosition = offset;
            _autoGeneratedSeats.Add(seatObj.transform);
        }

        Debug.Log($"[Table {tableNumber}] Auto-generated {count} fallback seat points.");
    }


    void OnDrawGizmosSelected()
    {
        Gizmos.color = IsOccupied ? Color.red : (Capacity > 0 ? Color.green : Color.gray);

        if (IsBarStand)
        {
            Gizmos.color = new Color(0.6f, 0.4f, 1f);
            Gizmos.DrawWireSphere(transform.position, chairDetectionDistance + 0.25f);
        }
        else
        {
            Vector3[] directions = { transform.forward, -transform.forward, transform.right, -transform.right };
            foreach (Vector3 dir in directions)
            {
                Vector3 checkPos = transform.position + dir * chairDetectionDistance;
                Gizmos.color = Color.cyan;
                Gizmos.DrawWireSphere(checkPos, chairDetectionRadius);
            }
        }

        if (_registeredChairs != null)
        {
            Gizmos.color = Color.green;
            foreach (Chair c in _registeredChairs)
            {
                if (c != null)
                {
                    Gizmos.DrawWireSphere(c.SeatTransform.position, 0.3f);
                    Gizmos.DrawLine(transform.position, c.SeatTransform.position);
                }
            }
        }

        if (_autoGeneratedSeats != null)
        {
            Gizmos.color = Color.yellow;
            foreach (Transform seat in _autoGeneratedSeats)
            {
                if (seat != null)
                {
                    Gizmos.DrawWireSphere(seat.position, 0.3f);
                    Gizmos.DrawLine(transform.position, seat.position);
                }
            }
        }

        Gizmos.color = Color.white;
        Gizmos.DrawWireSphere(transform.position, 0.15f);
    }
}