using System.Collections.Generic;
using UnityEngine;

/// <summary>
/// Represents a table in the restaurant with capacity and seat points for clients.
/// </summary>
public class Table : MonoBehaviour
{
    [Header("Table Properties")]
    public int tableNumber = 1;

    [Header("Chair-Based Capacity")]
    [Tooltip("Distance from the table center to check for chairs on each side.")]
    public float chairDetectionDistance = 1.1f;
    [Tooltip("Radius of the detection sphere at each side.")]
    public float chairDetectionRadius = 0.5f;
    [Tooltip("Layer where chairs are located for detection.")]
    public LayerMask chairLayer;

    [SerializeField] private List<Chair> _registeredChairs = new();
    private float _nextScanTime = 0f;
    private const float SCAN_INTERVAL = 0.5f;

    [Header("Food Placement")]
    [Tooltip("Transform point where food will be placed. If null, table center will be used.")]
    public Transform foodPoint;

    [Header("Auto-Generation (Fallback / Debug)")]
    [Tooltip("If true and no chairs are registered, auto-generate seat points for testing.")]
    public bool autoGenerateSeats = false;
    public float seatRadius = 1.5f;
    private List<Transform> _autoGeneratedSeats = new();

    public int Capacity => _registeredChairs.Count > 0 ? _registeredChairs.Count : _autoGeneratedSeats.Count;

    public bool IsOccupied { get; private set; }
    public ClientGroup OccupyingGroup { get; private set; }

    public bool IsPlaced { get; private set; }

    private PlaceableObject _placeable;
    private bool _wasStoraged;

    void Awake()
    {
        if (_registeredChairs == null) _registeredChairs = new List<Chair>();

        if (autoGenerateSeats)
        {
        }
    }

    void Start()
    {
        _placeable = GetComponent<PlaceableObject>();
        RestaurantManager.Instance?.RegisterTable(this);
        if (_placeable == null || !_placeable.Storaged)
        {
            IsPlaced = true;
            _wasStoraged = false;
            RestaurantManager.Instance?.TablePlaced(this);
        }
        else
        {
            IsPlaced = false;
            _wasStoraged = true;
        }
    }

    void Update()
    {
        if (Time.time >= _nextScanTime)
        {
            _nextScanTime = Time.time + SCAN_INTERVAL;
            ScanForChairs();
        }
        if (_placeable != null)
        {
            bool isCurrentlyStored = _placeable.Storaged;

            if (isCurrentlyStored && !_wasStoraged)
            {
                IsPlaced = false;
                _wasStoraged = true;
                RestaurantManager.Instance?.TableStored(this);
            }
            else if (!isCurrentlyStored && _wasStoraged)
            {
                IsPlaced = true;
                _wasStoraged = false;
                RestaurantManager.Instance?.TablePlaced(this);
            }
        }
    }

    void OnDestroy()
    {
        if (IsPlaced)
        {
            RestaurantManager.Instance?.TableStored(this);
        }
        RestaurantManager.Instance?.UnregisterTable(this);
    }

    public void Reserve(ClientGroup group)
    {
        if (group == null) return;

        if (group.Size > Capacity)
        {
            Debug.LogWarning($"[Table {tableNumber}] Group size {group.Size} exceeds capacity {Capacity}!");
        }

        IsOccupied = true;
        OccupyingGroup = group;
        Debug.Log($"[Table {tableNumber}] Reserved for {group}");
    }

    public void FreeTable(ClientGroup group)
    {
        if (!IsOccupied || OccupyingGroup != group) return;

        RestaurantManager.Instance?.FreeGroupTables(group);
    }

    public void ClearReservation()
    {
        IsOccupied = false;
        OccupyingGroup = null;
        Debug.Log($"[Table {tableNumber}] Freed");
    }

    public void ScanForChairs()
    {
        if (!IsPlaced)
        {
            if (_registeredChairs.Count > 0)
            {
                _registeredChairs.Clear();
                RestaurantManager.Instance?.TablePlaced(this);
            }
            return;
        }

        int previousCount = _registeredChairs.Count;
        _registeredChairs.Clear();

        Vector3[] directions = { transform.forward, -transform.forward, transform.right, -transform.right };

        foreach (Vector3 dir in directions)
        {
            if (_registeredChairs.Count >= 4) break;

            Vector3 checkPos = transform.position + dir * chairDetectionDistance;
            Collider[] hits = Physics.OverlapSphere(checkPos, chairDetectionRadius, chairLayer);

            Chair bestChair = null;
            float bestDist = float.MaxValue;

            foreach (Collider hit in hits)
            {
                Chair chair = hit.GetComponentInParent<Chair>();
                if (chair == null || !chair.IsPlaced) continue;

                if (_registeredChairs.Contains(chair)) continue;

                float dist = Vector3.Distance(checkPos, chair.transform.position);
                if (dist < bestDist)
                {
                    bestDist = dist;
                    bestChair = chair;
                }
            }

            if (bestChair != null)
            {
                _registeredChairs.Add(bestChair);
            }
        }

        if (_registeredChairs.Count != previousCount)
        {
            Debug.Log($"[Table {tableNumber}] Capacity changed: {_registeredChairs.Count}");
            RestaurantManager.Instance?.TablePlaced(this);
        }
    }

    public void RegisterChair(Chair chair) { ScanForChairs(); }

    public void UnregisterChair(Chair chair) { ScanForChairs(); }

    public List<Transform> GetSeatPoints()
    {
        if (_registeredChairs.Count > 0)
        {
            List<Transform> seats = new List<Transform>(_registeredChairs.Count);
            foreach (Chair c in _registeredChairs)
            {
                if (c != null)
                    seats.Add(c.SeatTransform);
            }
            return seats;
        }
        if (autoGenerateSeats)
        {
            if (_autoGeneratedSeats.Count == 0)
                GenerateSeatPoints();
            return _autoGeneratedSeats;
        }

        Debug.LogWarning($"[Table {tableNumber}] GetSeatPoints called but no chairs are registered and autoGenerateSeats is disabled!");
        return new List<Transform>();
    }
    public bool CanPlaceFood()
    {
        if (!IsOccupied || OccupyingGroup == null) return false;

        foreach (var member in OccupyingGroup.Members)
        {
            if (member != null && member.CurrentState == Client.State.WaitingForFood)
                return true;
        }

        return false;
    }

    public void PlaceFood(Food food)
    {
        if (food == null || OccupyingGroup == null) return;
        Transform targetPoint = foodPoint != null ? foodPoint : this.transform;
        food.PlaceOnTable(targetPoint);
        foreach (var member in OccupyingGroup.Members)
        {
            if (member != null)
            {
                member.ReceiveFood();
            }
        }

        Debug.Log($"[Table {tableNumber}] Food {food.foodName} served to group {OccupyingGroup.GroupID}");
    }

    private void GenerateSeatPoints()
    {

        foreach (Transform s in _autoGeneratedSeats)
            if (s != null) Destroy(s.gameObject);
        _autoGeneratedSeats.Clear();

        int count = Capacity > 0 ? Capacity : 4;
        for (int i = 0; i < count; i++)
        {
            GameObject seatObj = new GameObject($"AutoSeat_{tableNumber}_{i + 1}");
            seatObj.transform.SetParent(transform);

            float angle = (360f / count) * i;
            float radians = angle * Mathf.Deg2Rad;
            Vector3 offset = new Vector3(
                Mathf.Cos(radians) * seatRadius,
                0f,
                Mathf.Sin(radians) * seatRadius
            );
            seatObj.transform.localPosition = offset;
            _autoGeneratedSeats.Add(seatObj.transform);
        }

        Debug.Log($"[Table {tableNumber}] Auto-generated {count} fallback seat points.");
    }


    void OnDrawGizmosSelected()
    {
        Gizmos.color = IsOccupied ? Color.red : (Capacity > 0 ? Color.green : Color.gray);

        Vector3[] directions = { transform.forward, -transform.forward, transform.right, -transform.right };
        foreach (Vector3 dir in directions)
        {
            Vector3 checkPos = transform.position + dir * chairDetectionDistance;
            Gizmos.color = Color.cyan;
            Gizmos.DrawWireSphere(checkPos, chairDetectionRadius);
        }

        if (_registeredChairs != null)
        {
            Gizmos.color = Color.green;
            foreach (Chair c in _registeredChairs)
            {
                if (c != null)
                {
                    Gizmos.DrawWireSphere(c.SeatTransform.position, 0.3f);
                    Gizmos.DrawLine(transform.position, c.SeatTransform.position);
                }
            }
        }

        if (_autoGeneratedSeats != null)
        {
            Gizmos.color = Color.yellow;
            foreach (Transform seat in _autoGeneratedSeats)
            {
                if (seat != null)
                {
                    Gizmos.DrawWireSphere(seat.position, 0.3f);
                    Gizmos.DrawLine(transform.position, seat.position);
                }
            }
        }

        Gizmos.color = Color.white;
        Gizmos.DrawWireSphere(transform.position, 0.15f);
    }
}